Create getauthenticationstateasync-was-called-before-setauthenticatio…
telerik/reporting-docs pull request #131
Opened 2020-11-24 09:18 UTC by nelci592

…nstate.md

2020-11-27 14:16 UTC, DimitarNikolovv06 reviewed
It's looking pretty good.

2020-11-27 14:16 UTC, DimitarNikolovv06 commented on knowledge-base/getauthenticationstateasync-was-called-before-setauthenticationstate.md
> +We require Singleton for our service, however, Singleton can't be used because the AuthenticationProvider requires Scoped. You can find more information in [Accessing an authenticated user outside of
Maybe we could say here "We require the use of a Singleton for our service".

2021-01-15 14:51 UTC, todorarabadzhiev requested changes
There are things that should be clarified

2021-01-15 14:51 UTC, todorarabadzhiev commented on knowledge-base/getauthenticationstateasync-was-called-before-setauthenticationstate.md
> +description: The issue was resolved using the GetIdentity method of our controller. The error will be described in a KB article.  Error 'GetAuthenticationStateAsync was called before SetAuthenticatio
I think you should re-write this description

2021-01-15 14:51 UTC, todorarabadzhiev commented on knowledge-base/getauthenticationstateasync-was-called-before-setauthenticationstate.md
> +We support accessing the current user inside the CustomReportSourceResolver using our own mechanism as described in [ASP.NET Core. How to use information from HttpContext in Custom Report Resolver](.
I don't understand the last sentence 'Although that not all dependencies are passed using dependency injection, note that this is only a proof that the approach works. '

2022-03-09 13:26 UTC, todorarabadzhiev commented on knowledge-base/getauthenticationstateasync-was-called-before-setauthenticationstate.md
> +Error 'GetAuthenticationStateAsync was called before SetAuthenticationState.' is thrown in a [Custom Report Source Resolver](../reporting/telerik-reporting-rest-custom-report-resolver) that uses **Ge
Use SLUG 
{%slug telerikreporting/using-reports-in-applications/host-the-report-engine-remotely/telerik-reporting-rest-services/rest-service-report-source-resolver/how-to-implement-a-custom-report-source-resolver%}

2022-03-09 13:26 UTC, todorarabadzhiev commented on knowledge-base/getauthenticationstateasync-was-called-before-setauthenticationstate.md
> +We support accessing the current user inside the CustomReportSourceResolver using our own mechanism as described in [ASP.NET Core. How to use information from HttpContext in Custom Report Resolver](.
Use SLUG
{%slug core-how-to-pass-information-from-httpcontext-to-reporting-engine%}

2022-03-09 15:30 UTC, todorarabadzhiev approved these changes

2022-03-09 15:30 UTC, merged