Create unable-to-get-report-parameters-report-cannot-be-resolved.md
telerik/reporting-docs pull request #288
Opened 2022-01-05 16:30 UTC by DimitarNikolovv06

2022-01-05 17:23 UTC, todorarabadzhiev requested changes
Consider clarifying in the section "Cause\Possible Cause(s)" that hosting the service on Azure or Linux is not a cause for the problem, but the frequent limitations related to GDI in these environments.

2022-01-05 17:23 UTC, todorarabadzhiev commented on knowledge-base/unable-to-get-report-parameters-report-cannot-be-resolved.md
> +- If the application with the reporting web service is deployed on Azure with **lower** than **Basic** [App Service plan](https://azure.microsoft.com/en-us/pricing/details/app-service/windows/).
These are not causes. The problem occurs more frequently in these environments due to their limitations. For example, due to restricted GDI.

2022-01-05 17:23 UTC, todorarabadzhiev commented on knowledge-base/unable-to-get-report-parameters-report-cannot-be-resolved.md
> +- If the application is to be deployed on Azure, make sure that the app service plan offers the required GDI+ APIs required in order for the service to be able to render the reports. From what we kno
Typo: "higher"

2022-01-11 06:29 UTC, nelci592 commented on knowledge-base/unable-to-get-report-parameters-report-cannot-be-resolved.md
> +- If the application with the reporting web service is run on a Linux system.
maybe "is running/runs"

2022-01-11 06:29 UTC, nelci592 commented on knowledge-base/unable-to-get-report-parameters-report-cannot-be-resolved.md
> +
You may also add the following suggestion:
The problem may be related also to permission to access the folder. For example, make sure that the "Copy to output directory" of the report file is set to True.

2022-02-15 10:26 UTC, todorarabadzhiev requested changes
You may also change the Unordered List to Ordered so that there is an easier correspondence between the issue and suggested solution

2022-02-15 10:26 UTC, todorarabadzhiev commented on knowledge-base/unable-to-get-report-parameters-report-cannot-be-resolved.md
> +- If the application with the reporting web service is deployed in an environment that heavily restricts the GDI APIs. An example of such a case would an Azure environment with **lower** than **Basic
"... such a case would BE an Azure environment with..."

2022-02-15 10:26 UTC, todorarabadzhiev commented on knowledge-base/unable-to-get-report-parameters-report-cannot-be-resolved.md
> +- The problem may be related to folder permissions to access the folder. For example, make sure that the "**Copy to output directory**" setting of the report file is set to **True**. This setting may
I think "The problem may be related to folder permissions" is enough, " to access the folder" is somehow repeating the previous one. Or you may change it to "The problem may be related to folder access permissions"

2022-02-15 10:26 UTC, todorarabadzhiev commented on knowledge-base/unable-to-get-report-parameters-report-cannot-be-resolved.md
> +- If the application is to be deployed on Azure, make sure that the app service plan offers the required GDI+ APIs required in order for the service to be able to render the reports. From what we kno
"required " is repeated twice around "GDI+ APIs"

2022-02-15 10:26 UTC, todorarabadzhiev commented on knowledge-base/unable-to-get-report-parameters-report-cannot-be-resolved.md
> +```
Insert 3 spaces before the code snippet, so that it is below the list item

2022-02-15 13:24 UTC, todorarabadzhiev approved these changes

2022-02-15 13:25 UTC, merged