Create styling-report-items.md
telerik/reporting-docs pull request #364
Opened 2022-03-04 15:13 UTC by DimitarNikolovv06

2022-03-04 15:15 UTC, DimitarNikolovv06 commented
I added the case with the Graph data points' styling that Vankata mentioned to a Notes section, if you know of any other specific cases, feel free to share.

2022-03-08 15:05 UTC, todorarabadzhiev requested changes
I think you should include the information that when you don't set a Styling property of a report item, it inherits the corresponding value from its parent.

"The Default property is used to set all borders widths at once." - Actually, this is also used when you don't set explicitly a border property. For example, if you set the Default and you set only the Top, then the Default will be applied to Bottom, Left, and Right only.

Instead of writing everywhere 'The default value is ...', consider adding this at the top or at the bottom of the cell with some styling, e.g. italic,  and the units if applicable like:
"default is '1 in'"
This way, it will be more visible.

2022-03-08 15:05 UTC, todorarabadzhiev commented on designing-reports/styling-reports/styling-report-items.md
> +                    <li>Underline - <strong>Boolean.</strong>Indicates whether this Font is underlined.</li>
Add space:
'<strong>Boolean.</strong>Indicates ' > '<strong>Boolean</strong>. Indicates '

2022-03-09 07:20 UTC, nelci592 approved these changes

2022-03-09 07:20 UTC, nelci592 commented on designing-reports/styling-reports/styling-report-items.md
> +description: Styling Report Items
You can consider different description. Maybe something like "The article provides the available properties that can be used for the report items styling."

2022-03-14 14:36 UTC, merged